name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to master branch
        uses: actions/checkout@v1
      - name: Setup NodeJs 13.x
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: add things
        run: git add README.md
             git add weather.json
             git add joke.json
             git add dogs.json
      - name: continue
        run: git rebase --continue
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GithubKey }}
